# Generated by Django 2.0.4 on 2018-04-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogItems',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=800)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('is_del', models.IntegerField(default=0)),
            ],
        ),
    ]
